### PR TITLE
feat: pass request context to mutate callback (#11)

### PR DESCRIPTION
**Pull request by markhughes**
This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [x] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [x] no

If yes, please describe the breakage.

### Please Describe Your Changes

Implements #11

### CODE REVIEW

**Comment by markhughes** [comment]
@shellscape what are your thoughts on this one?

**Comment by shellscape** [comment]
I'm swamped right now, but this PR is at the top of my list.

**Comment by shellscape** [comment]
I'm good with the concept for this, but I'd like `requestContext` added to the `data` parameter, which will mean upgrading the `LogMutateData` type.

**Comment by markhughes** [comment]
Thanks! I applied the feedback, and updated the test snapshots

**Comment by shellscape** [comment]
You're almost there. Not quite what I was getting after:

```ts
export type LogMutateData = Record<string, string> & { context: GraphQLRequestContext };
```

That's basically equivalent to:

```ts
export interface LogMutateData {
  [key: string]: string;
  context: GraphQLRequestContext;
}
```

I just don't have a preference to either representation :)

Then you don't have to change the signature here https://github.com/shellscape/apollo-log/pull/12/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L53-L54, and your log call looks like this:

```ts
events.didEncounterErrors && log(operationId, { event: 'errors', errors, context });
```

That makes it easier for users to consume, and it's typed properly to show as a distinct key in `LogMutateData`

**Comment by markhughes** [comment]
Thanks @shellscape sorry for slow response it got busy. I've applied your feedback & adjusted the tests :)

**Comment by markhughes** [comment]
Hey @shellscape any feedback on this one? :)

**Comment by shellscape** [comment]
thanks!

**Pull request merged**
